
// DO NOT MODIFY
// Auto Generated by vite-sveltekit-telephone
export const functionMap: Record<string, any> = {}

import * as f0 from "$lib/tele/e2e.telephone";
functionMap["src/lib/tele/e2e.telephone.ts"] = f0;
